server:
  port: 80

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE

spring:
  elasticsearch:
    rest:
      uris:
        - ${ELASTIC_HOST:localhost}:9200
      connection-timeout: 1s
      read-timeout: 1m
      password:
      username:
